CREATE TABLE member
(
    user_no   NUMBER(4)
        CONSTRAINT MEMB_NO_PK PRIMARY KEY,
    user_name VARCHAR2(20 CHAR)
        CONSTRAINT MEMB_NAME_NN NOT NULL,
    user_id   VARCHAR2(20 CHAR)
        CONSTRAINT MEMB_ID_UK UNIQUE
        CONSTRAINT MEMB_ID_NN NOT NULL,
    user_pw   VARCHAR2(20 CHAR)
        CONSTRAINT MEMB_PW_NN NOT NULL,
    user_mail VARCHAR2(50 CHAR)
        CONSTRAINT MEMB_MAIL_UK UNIQUE
        CONSTRAINT MEMB_MAIL_NN NOT NULL,
    user_tel  VARCHAR2(15 CHAR)
        CONSTRAINT MEMB_TEL_UK UNIQUE
        CONSTRAINT MEMB_TEL_NN NOT NULL,
    user_gen  CHAR(1)
        CONSTRAINT MEMB_GEN_CK CHECK (user_gen IN ('F', 'M', 'N'))
        CONSTRAINT MEMB_GEN_NN NOT NULL,
    user_avt  NUMBER (4)
        CONSTRAINT MEMB_AVT_FK REFERENCES avatar(avt_no)
        CONSTRAINT MEMB_AVT_NN NOT NULL,
    joindate  DATE    DEFAULT sysdate
        CONSTRAINT MEMB_JOIN_NN NOT NULL,
    isShow    CHAR(1) DEFAULT 'N'
        CONSTRAINT MEMB_SHOW_CK CHECK (isshow IN ('Y', 'N'))
        CONSTRAINT MEMB_SHOW_NN NOT NULL
);

CREATE TABLE avatar
(
    avt_no    NUMBER(4)
        CONSTRAINT AVT_NO_PK PRIMARY KEY,
    avt_sname VARCHAR2(50 CHAR)
        CONSTRAINT AVT_SNAME_NN NOT NULL,
    avt_gen   CHAR(1)
        CONSTRAINT AVT_GEN_CK CHECK (avt_gen IN ('F', 'M', 'N'))
        CONSTRAINT AVT_GEN_NN NOT NULL,
    avt_sdir  VARCHAR2(100 CHAR)
        CONSTRAINT AVT_SDIR_NN NOT NULL,
    isShow    CHAR(1) DEFAULT 'N'
        CONSTRAINT AVT_SHOW_CK CHECK (isshow IN ('Y', 'N'))
        CONSTRAINT AVT_SHOW_NN NOT NULL
);

CREATE TABLE board
(
    bo_no    NUMBER(4)
        CONSTRAINT BO_NO_PK PRIMARY KEY,
    bo_userno    NUMBER(4)
        CONSTRAINT BO_USERNO_FK REFERENCES member(user_no)
        CONSTRAINT BO_USERNO_UK UNIQUE
        CONSTRAINT BO_USERNO_NN NOT NULL,
    bo_name  VARCHAR2(20 CHAR)
        CONSTRAINT BO_NAME_NN NOT NULL,
    bo_field VARCHAR2(200 CHAR)
        CONSTRAINT BO_FIELD_NN NOT NULL,
    bo_wdate DATE DEFAULT sysdate
        CONSTRAINT BO_WDATE_NN NOT NULL
);



